# -*- coding: utf-8 -*-
"""lab4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TAF-Z5ehDlrn8qbUI0GPfeIPhsxnyTWE
"""

import json
import yaml

# Чтение данных из файла в формате JSON
with open('data.json', 'r') as json_file:
    data = json.load(json_file)

# Конвертация в формат YAML
yaml_data = yaml.dump(data, default_flow_style=False)

# Запись данных в файл в формате YAML
with open('data.yaml', 'w') as yaml_file:
    yaml_file.write(yaml_data)